### ISSUE TITLE
Do a communication with a database

### ISSUE THREAD

**Issue by TARGAZ** [TARGAZ/SE-G7#1]

**Comment by TARGAZ** [comment]
Link to the database for having accesse to password and login and data

**Comment by TARGAZ** [comment]
# Definition of done°/
The issue will be finished when the software can read and write : 
- Login
- Password
- Information about the user
In the database

## Task°/
- [ ] Read login and password
- [ ] Write new login and password
- [ ] Read information about the user
- [ ] Write information about the user

**Comment by mislavmatijevic** [comment]
I liked how you experimented with opening and closing of the issue! 😃 However, notice that it's still marked "Done" in the project. That's not a problem to me, but you should be careful in actual projects.
