### ISSUE TITLE
Do form for student to enter their infomation

### ISSUE THREAD

**Issue by TARGAZ** [TARGAZ/SE-G7#3]

**Comment by TARGAZ** [comment]
# Definition of done°/
The issue will be finished when the user can :
- Read his information
- Write his information

## Task°/
- [ ] Do from for writing his information
- [ ] Make sure information is at the right place and correctly right
Example : phone number is in the phone number categories and correctly right 
- [ ] Do a readable document with all of his information
