### ISSUE TITLE
Do a graphique interface

### ISSUE THREAD

**Issue by TARGAZ** [TARGAZ/SE-G7#5]

**Comment by TARGAZ** [comment]
# Description of done°/
The issue will be finished when the software has a graphic interface

## Task°/
- [ ] Do a graphic interface to login
- [ ] Do a graphic interface for writing in the form
- [ ] Do a graphic interface to read information
- [ ] Do a graphic interface for administrator

**Comment by mislavmatijevic** [comment]
Great idea to explain the issue in greater detail! Anyhow, it would be advisable to write this description in the issue creation form rather than in a later separate comment.
